### ISSUE TITLE
Edit the Comment Text

### ISSUE THREAD

**Issue by NorthwoodsCreative** [johnregan3/simple-custom-css#15]
I just want to suggest an add to the next update. While helping in Wordpress support forums I suggest this plugin, but a lot of newbies get confused with the comment text in the editor area.

What happens is they see /* Enter Your Custom CSS Here */ and then add the code inside the comment section.

Maybe change it to /* Enter Your Custom CSS Under Here */ or something like that.

Thanks.

**Comment by johnregan3** [comment]
@NorthwoodsCreative  Awesome tip, man.  Thanks!
