### ISSUE TITLE
Support for SSL, serving css over HTTPS

### ISSUE THREAD

**Issue by georgeedwards** [johnregan3/simple-custom-css#18]
I use wooCommerce on my site and I have just forced HTTPS redirect for the Checkout flow. However, when I do this, my custom CSS is blocked. I get:

>Mixed Content: The page at 'https://www.myDomain.co.uk/blog/product/myProduct/' was loaded over HTTPS, but requested an insecure stylesheet 'http://www.myDomain.co.uk/blog/?sccss=1&ver=fe62ddea3ed1898e6866564ccdc86c01'. This request has been blocked; the content must be served over HTTPS.

How can I fix this / work around it?

**Comment by johnregan3** [comment]
Hi @georgeedwards.  This issue has been finally fixed.  Please download the latest release and check it out!
